#!/bin/bash
set -e

# Install SQuIDS
git clone https://github.com/jsalvado/SQuIDS.git $HOME/SQuIDS
cd $HOME/SQuIDS
./configure --prefix=$CONDA_PREFIX
make -j$(nproc)
make install
cd -

# Install nuSQuIDS using pip (uses pybind11, not Boost.Python)
pip install .
